name: Upload Coda Pack

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  upload-coda-pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: true
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: lts/*
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - name: Upload and Release Coda Pack
        shell: bash
        run: |
          set -euo pipefail
          TAG="${{ github.event.release.tag_name }}"
          VERSION="${TAG#v}"
          echo "$VERSION" > VERSION
          npx coda register ${{ secrets.CODA_API_TOKEN }}
          npx coda upload pack.ts --apiToken ${{ secrets.CODA_API_TOKEN }}
          npx coda release pack.ts "$VERSION" --notes "$TAG" --apiToken ${{ secrets.CODA_API_TOKEN }}